name: Failure workflow (for test purpose only)

on:
  workflow_dispatch:

jobs:
  failure:
    name: failure
    runs-on: ubuntu-latest
    steps:
      - name: Failure
        run: |
          exit 3